export const ADD_STATION_STEPS = {
  STATION_TYPE: 'STATION_TYPE',
  GENERAL_INFORMATION: 'OTP_CODE',
  SUCCESS: 'SUCCESS',
  USER_INFO: 'USER_INFO',
  BUSINESS_INFO: 'BUSINESS_INFO',
  BUSINESS_LOCATION: 'BUSINESS_LOCATION',
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
}
