export const ADD_STATION_STEPS = {
  STATION_TYPE: 'STATION_TYPE',
  GENERAL_INFORMATION: 'GENERAL_INFORMATION',
  STATION_AMENITIES: 'STATION_AMENITIES',
  CONNECT_YOUR_BANK: 'CONNECT_YOUR_BANK',
  CONNECT_YOUR_SYSTEM: 'CONNECT_YOUR_SYSTEM',
  FINALIZE: 'FINALIZE',
}