export const SIGN_UP_STEPS = {
  EMAIL: 'EMAIL',
  OTP_CODE: 'OTP_CODE',
  SUCCESS: 'SUCCESS',
  USER_INFO: 'USER_INFO',
  BUSINESS_INFO: 'BUSINESS_INFO',
  BUSINESS_LOCATION: 'BUSINESS_LOCATION',
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
}
